import Head from "next/head";
import Quiz from "@/components/Quiz/Quiz";
import Layout from "@/containers/Layout/Layout";
export default function Home() {
  return (
    <>
      <Head>
        <title>Quiz Application</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Quiz />
      </Layout>
    </>
  );
}
